services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE='
      - 'MONGO_INITDB_ROOT_PASSWORD='
      - 'MONGO_INITDB_ROOT_USERNAME='
    ports:
      - '27017'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
